// Code generated by Prismic. DO NOT EDIT.

import Experience from "./Experience/index.svelte";
import GithubCalenderContributions from "./GithubCalenderContributions/index.svelte";
import HeroSection from "./HeroSection/index.svelte";
import Portfolio from "./Portfolio/index.svelte";
import Skills from "./Skills/index.svelte";

export const components = {
	experience: Experience,
	github_calender_contributions: GithubCalenderContributions,
	hero_section: HeroSection,
	portfolio: Portfolio,
	skills: Skills
};